### ISSUE TITLE
Ingested metadata can not be displayed in frontend

### ISSUE THREAD

**Issue by linupi** [SciCatProject/documentation#10]
I have tried to upload metadata in as provided in the `ingestManual.md` to a SciCat instance based on _scicatlive_ and realized that there must be some issues with the provided examples.

E.g. in 
https://github.com/SciCatProject/documentation/blob/5a38140f009dde3ec8ab6cc2d3eec681120f3d34/Ingestor/ingestManual.md?plain=1#L402

there is 
```
                    "Ring current": {
                        "v": 0.402246,
                        "u": "A"
                    },
```

but to me it seems like only 

```
                    "Ring current": {
                        "value": 0.402246,
                        "unit": "A"
                    },
```
works fine.

Further there are examples using `units` instead of `unit` which also don't work for me. E.g.

https://github.com/SciCatProject/documentation/blob/5a38140f009dde3ec8ab6cc2d3eec681120f3d34/Ingestor/ingestManual.md?plain=1#L317

In case my observations are correct I am happy to provide a PR improving the doc related to this.

**Comment by stephan271** [comment]
Hi, your observations are almost correct. SciCat supports both v/u and value/unit in the latest versions (this may depend on some configuration settings, however I am not 100% sure). But for the documentation I think the best would be to only use the value/unit spelling (and not "units"). So please go ahead with a PR for that, thanks for helping.

**Comment by nitrosx** [comment]
@linupi : thank you so much for your contribution. 
Please reach out if you have any question, issue or any improvement to suggest.
