### ISSUE TITLE
Links between Dataset and Project

### ISSUE THREAD

**Issue by paulmillar** [SciCatProject/documentation#16]
When first investigating SciCat's data model, I looked at [the data model page](https://scicatproject.github.io/documentation/Development/Data_Model.html), and in particular, [the UML-style diagram](https://scicatproject.github.io/documentation/Development/img/Class_Diagram.PNG).

I was quite surprised to see (apparently) no link between Dataset and Proposal.

Digging into the code, I see that Dataset has two "sub-classes" RawDataset and DerivedDataset, as described in the page.

If I've understood the code correctly, it is only RawDataset that has a link to a Proposal, while DerivedDataset has a (somewhat loose) link to some list of source Dataset; providing a provenance chain.

Assuming this is broadly correct, I have a couple of comments:

1. perhaps it would make sense to document how Datasets are connected to Proposals?

There is (perhaps) a limit to how much information can be included in a diagram, but I think adding RawDataset and DerivedDataset would have value, as it would allow someone to see how RawDataset is linked to a Proposal, and how DerivedDataset is link to source Dataset objects.

In any case, I think the text description of RawDataset should be updated to mention that there is a link to the Proposal.

2. DerivedDataset seems rather loosely linked to the Proposal

Assuming the connection is made through the provenance trail and that provenance information is optional, then it might be worth emphasising that the provenance information is important and what is the consequence of not providing it: a lack of connection to the corresponding Proposal.

**Comment by stephan271** [comment]
Before answering: you sometimes mention proposals and sometimes "projects" ? What is the difference, if any ?

**Comment by paulmillar** [comment]
Sorry, me bad.  I meant Proposal.  I've updated the text to fix those problems.

**Comment by stephan271** [comment]
Assuming Project=Proposal in your comment: all your assumptions are correct and your suggestions for improving the documentation are very good, thanks ! Do you see a chance to help us with that by preparing a PR for that with the necessary changes ? Concerning the derived datasets: adding a direct relation to proposals would be an option, however one would need to have the option to relate it to more than one proposal in case the analysis combines data from different proposals. Via the links to the raw datasets that many to many relation is implemented, although,as you pointed out ,only in an optional way.

**Comment by paulmillar** [comment]
I've created a pull-request that updates the text documentation.  Unfortunately, I think updating the diagram is beyond what I can reasonably do right now.  I hope the text is reasonable: please feel free to comment.

I don't have a strong opinion on whether it makes sense to have a proposal within DerivedDataset.  Certainly, the provenance information provides useful information that can lead to the Proposal(s).

I could see a use for including a proposal ID within the DerivedData: it could describe through which proposal the computing resources (needed for the analysis) are provided.

For example, someone working on `Proposal Z` could test their analysis software using existing datasets, originally from `Proposal X` and `Proposal Y`.  The resulting DerivedDataset would have proposalId `Z` and inputDatasets `["rawdataset-X-a", "rawdataset-Y-b"]`, where `rawdataset-X-a` would have proposalId `X` (and similarly for `rawdataset-Y-b`).

That said, this is purely observations and speculation on my part.  I don't (yet) have a concrete use-case to justify this change.

**Comment by stephan271** [comment]
Thanks for the PR ! Just merged.
