### ISSUE TITLE
Zip-Service

### ISSUE THREAD

**Issue by ChuckMoe** [SciCatProject/documentation#18]
When using the zip service, new users might not immediately know where they can find the jwt secret needed for the communication with it. 

What do you think about adding a section about the zip service to the documentation? Or should this information be added to the zip service repository?

**Comment by nitrosx** [comment]
@ChuckMoe : It would be a great idea to add a section to the documentation.

**Comment by nitrosx** [comment]
Closing issue as PR with updated documentation has been merged
